### ISSUE TITLE
Official support for Electron

### ISSUE THREAD

**Issue by stoyan-stoyanov** [crossbario/autobahn-js#356]
I am building an electron app with ReactJS and AutobahnJS. Autobahn works fine before wrapping the app with electron but it stops working with electron. 

I get the following error message:
Unhandled exception raised:  TypeError: Cannot read property 'on_internal_error' of undefined
    at Connection../node_modules/autobahn/lib/connection.js.Connection._create_transport (connection.js:152)
    at retry (connection.js:279)
    at Connection../node_modules/autobahn/lib/connection.js.Connection.open (connection.js:408)

I am using autobahn version 18.3.2.
and electron version 2.0.2.

I saw that this was pointed out in other issues but I am also loading autobahn with 
var autobahn = require('autobahn') 

Any help would be appreciated!

**Comment by marablayev** [comment]
@oberstet Hi, actually it is an error. Here is [pull request](https://github.com/crossbario/autobahn-js/pull/366). self was not defined in function so when error catched it could not read on_internal_error from self._options.

Sorry, if I did wrong with pull request and commit. It was first time I did it in code :)

**Comment by oberstet** [comment]
@marablayev ah, ok, thanks! merged @stoyan-stoyanov it was a bug actually, sorry. the merged PR should fix the issue (haven't tested myself).

**Comment by RBukharov** [comment]
Hello. I guess here is the only error output was fixed but not the initial issue. I faced with the same problem: first when try to use autobahn with electron I've got the same message: "Unhandled exception raised: TypeError: Cannot read property 'on_internal_error' of undefined".

Then I tried with the new code after merge the linked PR (btw there was no release on npm since merge): 

start electron app, open console and execute:

```javascript
var connection = new autobahn.Connection({url: 'ws://127.0.0.1:8080/', realm: 'realm1'});

connection.onopen = function (session) {

   // 1) subscribe to a topic
   function onevent(args) {
      console.log("Event:", args[0]);
   }
   session.subscribe('some.channel', onevent);
};

connection.open();
```

Then I see the following:

```
util.js:279 could not create WAMP transport 'websocket':  TypeError: o is not a constructor
    at s.create (websocket.js:102)
    at u._create_transport (connection.js:149)
    at e (connection.js:286)
    at u.open (connection.js:415)
    at <anonymous>:1:12
WCTu.e.handle_error @ util.js:279
u._create_transport @ connection.js:156
e @ connection.js:286
u.open @ connection.js:415
(anonymous) @ VM179:1

connection.js:159 could not create any WAMP transport
```

autobahn version 18.3.2.
electron version 2.0.5.

**Comment by RBukharov** [comment]
@oberstet, I'm sorry but #366 fix the only error output as I wrote above (now instead of `"Unhandled exception raised: TypeError: Cannot read property 'on_internal_error' of undefined"` appear the real error).
 
I tested it on the code from master and got the error described in my previous comment. So the initial problem still not resolved: Autobahn is not working with Electron. Should I create a new issue?

**Comment by oberstet** [comment]
@RBukharov ok, I see, sorry. if you wanna have it fixed quickly, a PR would be best of course;)

**Comment by RBukharov** [comment]
@oberstet, I found that browser implementation of WebSocket works well with Electron (maybe that was obvious :) ) but environment detection in your code use node implementation for this case. 
I fixed it in pull-request #370

**Comment by RBukharov** [comment]
#370 is merged. I think now it's time to close this issue.

**Comment by om26er** [comment]
> But having updated to the latest v18.10.2 I get this error:

Do you have a minimal reproducible program for that, I'll take a look into this. We should probably open a new bug report for your issue.

**Comment by oberstet** [comment]
reliably detecting WebSocket support (and the flavor thereof) across all run-times/envs ABJS supports .. is annoying.

given the history of this stuff coming back again and again (glitches .. fix .. new glitch): mid/long term we need CI on this executing all the envs/run-times to really nail it - and make sure it doesnt pop up again.

adding CI for all this is the actual work here

**Comment by peterforgacs** [comment]
> For me v10.3.2 was working fine with electron, I guess this is because connection is established from the `main` process, not the `renderer`. But having updated to the latest v18.10.2 I get this error:
> 
> > could not create WAMP transport 'websocket':  browser does not support WebSocket or WebSocket in Web workers
> > could not create any WAMP transport
> 
> Nothing has changed in my code, autobahn is still called from the main process. Downgrading to v18.3.2 makes everything work again. ¯_(ツ)_/¯

I have encountered the same problem, i think its caused by this commit: 
https://github.com/crossbario/autobahn-js/commit/cc45dc38f178b91943c554c464b30c02bff8eff7

It's pretty strange since the documentation states that the autoping funcionality is only active in NodeJs/Electron. (https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md)

I think the broader issue is that there is no information whether electron is running with nodeintegration enabled and where the connection is being made.  I would be willing to work on this if i could get some help / pointers with this https://github.com/crossbario/autobahn-js/issues/315.

**Comment by oberstet** [comment]
> I think the broader issue is that there is no information whether electron is running with nodeintegration enabled and where the connection is being made. 

not only that: the broader issue really is: it is non-trivial to robustly detect the actual environment in which the library (autobahn) runs .. the JS universe is big;)

we are at a point where a fix at one end (make env X work) has a significant chance of breaking env Y - this isn't sustainable obviously.

---

as a first step, we might to clearly list and define all the envs that this library is supposed to run under and support.

1. browser (with builtin websocket)
2. nodejs (plain headless, with `ws` library for websocket)
* ...

**Comment by BHuys** [comment]
I can verify that the issue is indeed caused by the check on global.process.versions.electron when you start the connection from main instead from renderer. My quick and rather dirty fix for now is to set this property to false before setting up my connection which runs independantly from my Electron windows.

 ```
if (global.process.versions.hasOwnProperty('electron')){
        delete global.process.versions.electron;
    }
// setup connection here
```
As stated before this is a dirty fix imo, I'm not sure what the implications are if you would use this, my project seems to run fine but I'll be checking this issue regulary.

**Comment by om26er** [comment]
this is already fixed in trunk, the next ABJS release will have the fix https://github.com/crossbario/autobahn-js/pull/479
