### ISSUE TITLE
TypeError: Cannot read property 'ca' of undefined

### ISSUE THREAD

**Issue by sherpya** [crossbario/autobahn-js#387]
in `lib/transport/websocket.js`:

```js
         if (self._options.url.startsWith('wss://')) {
            // Using TLS
            // Only using the known working flags in the options.
            // https://nodejs.org/api/https.html#https_https_request_options_callback
            options.ca = self._options.tlsConfiguration.ca;
            options.cert = self._options.tlsConfiguration.cert;
            options.key = self._options.tlsConfiguration.key;
            options.rejectUnauthorized = false;
         }
```
please provide a default, if I comment out these tlsConfig lines the connect does work

**Comment by sherpya** [comment]
I think `self._options.tlsConfiguration = self._options.tlsConfiguration || {}` somewhere should be enough

**Comment by om26er** [comment]
> please provide a default, if I comment out these tlsConfig lines the connect does work

Why do you comment out those lines ?

**Comment by sherpya** [comment]
@om26er to quick check if the connection would work without, now I'm passing `tlsConfiguration: {}` in the options, but I think it should be optional

**Comment by johannwagner** [comment]
Sorry about this. I broke this with my PR #361. I just created a PR to fix this.

**Comment by johannwagner** [comment]
@sherpya If you have further questions about those lines of code, you can contact me.

**Comment by oddjobz** [comment]
Ok, I just came across this issue trying to help someone else with the same problem. The client-side fix is to include 'tlsConfiguration: {}' as a part of the 'transport' section, which seems a little counter-intuitive. Is there any chance we could go with something like;
```python
if (self._options.url.startsWith('wss://') && self._options.tlsConfiguration ) {
```
and if necessary, an an "else options.ca = null" .. etc ..
i.e. it's quite valid to have a wss connection string without having to set up a client certificate, so could the 'tlsConfiguration' be optional from the client perspective?

**Comment by oddjobz** [comment]
@johannwagner Ah, sorry, have now looked at the PR changes .. which looks like it'll fix it to me :) .. I left a comment on the code, maybe a slight optimisation?

**Comment by gywgithub** [comment]
I use `yarn` for dependency package installation, and the project works well.
`node: v10.12.0`
`yarn: v1.10.1`
`"devDependencies": {
    "autobahn": "^18.3.2",
    "ws": "^5.2.1"
  }`

**Comment by johannwagner** [comment]
@gywgithub Can you specify your autobahn version, which is installed? Your snippet only shows, that the version has to be `18.3.2` or above. This issue only applies for newer versions than `18.3.2`, because I implemented this feature to use TLS client authentication in June.

**Comment by gywgithub** [comment]
@johannwagner   I use the latest docker image.  Crossbar v18.9.2

**Comment by KrishnaPG** [comment]
Came across this while facing the same problem. The `autobahn` version I have is latest:
````
    "autobahn": "^18.10.2",
````
I am trying to use it with the demo code, which has demo server: 
`````
		{
			"url": "wss://demo.crossbar.io/ws", 
			"realm": "realm1"
		}
`````

**Comment by KillermenBE** [comment]
@om26er This problem isn't fixed. On 18.10.2 we still have this issue

**Comment by johannwagner** [comment]
Can you show us your configuration?

**Comment by nijuyr** [comment]
@KillermenBE @KrishnaPG @johannwagner 
The version `18.10.2` does not include the fix PR https://github.com/crossbario/autobahn-js/pull/393/files
The fix PR is still in `master` branch but yet to be released.

And why has this issue been closed? because the fix was merged into master? But it hasn't been released yet!

**Comment by KillermenBE** [comment]
@nijuyr @johannwagner If you use the master-branch, the problem is fixed. Current workaround is to get the master-branch with npm.
